-- ============================================================
-- 国资委数据采集交换平台接口相关表 - 达梦数据库版本
-- ============================================================

-- ============================================================
-- 统一操作日志表 (所有接口调用的总日志)
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_INTERFACE_LOG" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "LOG_ID" VARCHAR(100) NOT NULL,
    "INTERFACE_TYPE" VARCHAR(50) NOT NULL,
    "INTERFACE_URL" VARCHAR(500),
    "REQUEST_METHOD" VARCHAR(10),
    "REQUEST_PARAMS" TEXT,
    "REQUEST_TIME" DATETIME,
    "RESPONSE_TIME" DATETIME,
    "COST_TIME" BIGINT,
    "RESPONSE_CODE" INT,
    "SERVICE_FLAG" VARCHAR(10),
    "RESPONSE_MSG" TEXT,
    "RESPONSE_BODY" TEXT,
    "FILE_NAME" VARCHAR(500),
    "FILE_SIZE" BIGINT,
    "FILE_PATH" VARCHAR(1000),
    "BUSINESS_TYPE" VARCHAR(50),
    "SOCIAL_CREDIT_CODE" VARCHAR(50),
    "STATUS" INT DEFAULT 0,
    "ERROR_MSG" TEXT,
    "RETRY_COUNT" INT DEFAULT 0,
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_INTERFACE_LOG" IS '接口调用统一日志表';
COMMENT ON COLUMN "T_INTERFACE_LOG"."ID" IS '主键ID';
COMMENT ON COLUMN "T_INTERFACE_LOG"."LOG_ID" IS '日志ID(UUID)';
COMMENT ON COLUMN "T_INTERFACE_LOG"."INTERFACE_TYPE" IS '接口类型: FILE_UPLOAD-数据报送, KEY_DOWNLOAD-密钥下载, TEMP_DOWNLOAD-采集目录下载, TASK_DOWNLOAD-任务下载, NOTICE_DOWNLOAD-通知下载, LOG_DOWNLOAD-日志下载';
COMMENT ON COLUMN "T_INTERFACE_LOG"."INTERFACE_URL" IS '接口地址';
COMMENT ON COLUMN "T_INTERFACE_LOG"."REQUEST_METHOD" IS '请求方法: GET/POST';
COMMENT ON COLUMN "T_INTERFACE_LOG"."REQUEST_PARAMS" IS '请求参数(JSON)';
COMMENT ON COLUMN "T_INTERFACE_LOG"."REQUEST_TIME" IS '请求时间';
COMMENT ON COLUMN "T_INTERFACE_LOG"."RESPONSE_TIME" IS '响应时间';
COMMENT ON COLUMN "T_INTERFACE_LOG"."COST_TIME" IS '耗时(毫秒)';
COMMENT ON COLUMN "T_INTERFACE_LOG"."RESPONSE_CODE" IS '响应状态码';
COMMENT ON COLUMN "T_INTERFACE_LOG"."SERVICE_FLAG" IS '服务标识: 0-失败, 1-成功, 2-无权限, 3-无新文件';
COMMENT ON COLUMN "T_INTERFACE_LOG"."RESPONSE_MSG" IS '响应消息';
COMMENT ON COLUMN "T_INTERFACE_LOG"."RESPONSE_BODY" IS '响应内容';
COMMENT ON COLUMN "T_INTERFACE_LOG"."FILE_NAME" IS '文件名称';
COMMENT ON COLUMN "T_INTERFACE_LOG"."FILE_SIZE" IS '文件大小(字节)';
COMMENT ON COLUMN "T_INTERFACE_LOG"."FILE_PATH" IS '文件保存路径';
COMMENT ON COLUMN "T_INTERFACE_LOG"."BUSINESS_TYPE" IS '业务类型';
COMMENT ON COLUMN "T_INTERFACE_LOG"."SOCIAL_CREDIT_CODE" IS '社会信用代码';
COMMENT ON COLUMN "T_INTERFACE_LOG"."STATUS" IS '处理状态: 0-未处理, 1-处理中, 2-处理成功, 3-处理失败';
COMMENT ON COLUMN "T_INTERFACE_LOG"."ERROR_MSG" IS '错误信息';
COMMENT ON COLUMN "T_INTERFACE_LOG"."RETRY_COUNT" IS '重试次数';
COMMENT ON COLUMN "T_INTERFACE_LOG"."REMARK" IS '备注';
COMMENT ON COLUMN "T_INTERFACE_LOG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_INTERFACE_LOG"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_INTERFACE_LOG"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_INTERFACE_LOG"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_INTERFACE_LOG"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE INDEX "IDX_INTERFACE_LOG_LOG_ID" ON "T_INTERFACE_LOG"("LOG_ID");
CREATE INDEX "IDX_INTERFACE_LOG_TYPE" ON "T_INTERFACE_LOG"("INTERFACE_TYPE");
CREATE INDEX "IDX_INTERFACE_LOG_REQ_TIME" ON "T_INTERFACE_LOG"("REQUEST_TIME");
CREATE INDEX "IDX_INTERFACE_LOG_STATUS" ON "T_INTERFACE_LOG"("STATUS");
CREATE INDEX "IDX_INTERFACE_LOG_BUS_TYPE" ON "T_INTERFACE_LOG"("BUSINESS_TYPE");

-- ============================================================
-- 数据报送记录表 (接口1: fileUpload)
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_FILE_UPLOAD_RECORD" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "LOG_ID" VARCHAR(100),
    "API_CODE" VARCHAR(50),
    "BUSINESS_TYPE" VARCHAR(50),
    "FILE_NAME" VARCHAR(500) NOT NULL,
    "FILE_SIZE" BIGINT,
    "FILE_PATH" VARCHAR(1000),
    "FILE_MD5" VARCHAR(100),
    "SOCIAL_CREDIT_CODE" VARCHAR(50),
    "UPLOAD_STATUS" INT DEFAULT 0,
    "SERVICE_FLAG" VARCHAR(10),
    "RESPONSE_MSG" TEXT,
    "PARSE_STATUS" INT DEFAULT 0,
    "PARSE_RESULT" TEXT,
    "ERROR_MSG" TEXT,
    "RETRY_COUNT" INT DEFAULT 0,
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_FILE_UPLOAD_RECORD" IS '数据报送记录表';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."ID" IS '主键ID';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."LOG_ID" IS '关联日志ID';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."API_CODE" IS 'API编码';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."BUSINESS_TYPE" IS '业务类型';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."FILE_NAME" IS '文件名称';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."FILE_SIZE" IS '文件大小(字节)';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."FILE_PATH" IS '文件保存路径';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."FILE_MD5" IS '文件MD5值';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."SOCIAL_CREDIT_CODE" IS '企业社会信用代码';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."UPLOAD_STATUS" IS '上传状态: 0-待处理, 1-处理中, 2-成功, 3-失败';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."SERVICE_FLAG" IS '服务标识: 0-失败, 1-成功, 2-无权限';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."RESPONSE_MSG" IS '响应消息';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."PARSE_STATUS" IS '解析状态: 0-未解析, 1-解析中, 2-解析成功, 3-解析失败';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."PARSE_RESULT" IS '解析结果(JSON)';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."ERROR_MSG" IS '错误信息';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."RETRY_COUNT" IS '重试次数';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."REMARK" IS '备注';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE INDEX "IDX_FILE_UPLOAD_LOG_ID" ON "T_FILE_UPLOAD_RECORD"("LOG_ID");
CREATE INDEX "IDX_FILE_UPLOAD_BUS_TYPE" ON "T_FILE_UPLOAD_RECORD"("BUSINESS_TYPE");
CREATE INDEX "IDX_FILE_UPLOAD_STATUS" ON "T_FILE_UPLOAD_RECORD"("UPLOAD_STATUS");
CREATE INDEX "IDX_FILE_UPLOAD_CREATE_TIME" ON "T_FILE_UPLOAD_RECORD"("CREATE_TIME");

-- ============================================================
-- 密钥证书表 (接口2: keyDownload)
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_KEY_CERTIFICATE" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "LOG_ID" VARCHAR(100),
    "KEY_ID" VARCHAR(100) NOT NULL,
    "BUSINESS_TYPE" VARCHAR(50),
    "KEY_VERSION" VARCHAR(50),
    "SM2_PUBLIC_KEY" TEXT,
    "SM4_KEY" TEXT,
    "SM2_PUBLIC_KEY_DECRYPTED" TEXT,
    "SM4_KEY_DECRYPTED" TEXT,
    "FILE_NAME" VARCHAR(500),
    "FILE_PATH" VARCHAR(1000),
    "DOWNLOAD_TIME" DATETIME,
    "STATUS" INT DEFAULT 0,
    "ACTIVE_TIME" DATETIME,
    "EXPIRE_TIME" DATETIME,
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_KEY_CERTIFICATE" IS '密钥证书表';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."ID" IS '主键ID';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."LOG_ID" IS '关联日志ID';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."KEY_ID" IS '密钥主键ID';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."BUSINESS_TYPE" IS '业务类型';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."KEY_VERSION" IS '密钥版本号';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."SM2_PUBLIC_KEY" IS 'SM2公钥(加密存储)';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."SM4_KEY" IS 'SM4密钥(加密存储)';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."SM2_PUBLIC_KEY_DECRYPTED" IS 'SM2公钥(解密后明文)';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."SM4_KEY_DECRYPTED" IS 'SM4密钥(解密后明文)';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."FILE_NAME" IS '密钥文件名';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."FILE_PATH" IS '文件保存路径';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."DOWNLOAD_TIME" IS '下载时间';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."STATUS" IS '状态: 0-未启用, 1-已启用, 2-已废弃';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."ACTIVE_TIME" IS '启用时间';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."EXPIRE_TIME" IS '过期时间';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."REMARK" IS '备注';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE UNIQUE INDEX "UK_KEY_CERT_KEY_ID" ON "T_KEY_CERTIFICATE"("KEY_ID");
CREATE INDEX "IDX_KEY_CERT_BUS_TYPE" ON "T_KEY_CERTIFICATE"("BUSINESS_TYPE");
CREATE INDEX "IDX_KEY_CERT_VERSION" ON "T_KEY_CERTIFICATE"("KEY_VERSION");
CREATE INDEX "IDX_KEY_CERT_STATUS" ON "T_KEY_CERTIFICATE"("STATUS");

-- ============================================================
-- 业务类型表 (接口3: tempDownload - 业务类型)
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_BUSINESS_TYPE" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "BUSINESS_ID" VARCHAR(100) NOT NULL,
    "BUSINESS_CODE" VARCHAR(50) NOT NULL,
    "BUSINESS_NAME" VARCHAR(200),
    "BUSINESS_DESC" TEXT,
    "STATUS" INT DEFAULT 1,
    "SORT_ORDER" INT DEFAULT 0,
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_BUSINESS_TYPE" IS '业务类型表';
COMMENT ON COLUMN "T_BUSINESS_TYPE"."ID" IS '主键ID';
COMMENT ON COLUMN "T_BUSINESS_TYPE"."BUSINESS_ID" IS '业务主键ID';
COMMENT ON COLUMN "T_BUSINESS_TYPE"."BUSINESS_CODE" IS '业务编码';
COMMENT ON COLUMN "T_BUSINESS_TYPE"."BUSINESS_NAME" IS '业务名称';
COMMENT ON COLUMN "T_BUSINESS_TYPE"."BUSINESS_DESC" IS '业务描述';
COMMENT ON COLUMN "T_BUSINESS_TYPE"."STATUS" IS '状态: 0-禁用, 1-启用';
COMMENT ON COLUMN "T_BUSINESS_TYPE"."SORT_ORDER" IS '排序';
COMMENT ON COLUMN "T_BUSINESS_TYPE"."REMARK" IS '备注';
COMMENT ON COLUMN "T_BUSINESS_TYPE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_BUSINESS_TYPE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_BUSINESS_TYPE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_BUSINESS_TYPE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_BUSINESS_TYPE"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE UNIQUE INDEX "UK_BUSINESS_TYPE_ID" ON "T_BUSINESS_TYPE"("BUSINESS_ID");
CREATE INDEX "IDX_BUSINESS_TYPE_CODE" ON "T_BUSINESS_TYPE"("BUSINESS_CODE");
CREATE INDEX "IDX_BUSINESS_TYPE_STATUS" ON "T_BUSINESS_TYPE"("STATUS");

-- ============================================================
-- 采集模板信息表 (接口3: tempDownload - 模板信息)
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_TEMPLATE_INFO" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "TEMPLATE_ID" VARCHAR(100) NOT NULL,
    "TEMPLATE_CODE" VARCHAR(50) NOT NULL,
    "TEMPLATE_NAME" VARCHAR(200),
    "TEMPLATE_VERSION" VARCHAR(50),
    "BUSINESS_ID" VARCHAR(100),
    "BUSINESS_CODE" VARCHAR(50),
    "TEMPLATE_DESC" TEXT,
    "FILE_NAME" VARCHAR(500),
    "FILE_PATH" VARCHAR(1000),
    "TEMPLATE_CONTENT_DECRYPTED" TEXT,
    "EXAMPLE_FILE_NAME" VARCHAR(500),
    "EXAMPLE_FILE_PATH" VARCHAR(1000),
    "DOWNLOAD_TIME" DATETIME,
    "STATUS" INT DEFAULT 0,
    "ACTIVE_TIME" DATETIME,
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_TEMPLATE_INFO" IS '采集模板信息表';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."ID" IS '主键ID';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."TEMPLATE_ID" IS '模板主键ID';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."TEMPLATE_CODE" IS '模板编码';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."TEMPLATE_NAME" IS '模板名称';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."TEMPLATE_VERSION" IS '模板版本号';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."BUSINESS_ID" IS '业务外键ID';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."BUSINESS_CODE" IS '业务编码';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."TEMPLATE_DESC" IS '模板描述';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."FILE_NAME" IS '模板文件名';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."FILE_PATH" IS '模板文件路径';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."TEMPLATE_CONTENT_DECRYPTED" IS '模板内容(解密后)';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."EXAMPLE_FILE_NAME" IS '示例文件名';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."EXAMPLE_FILE_PATH" IS '示例文件路径';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."DOWNLOAD_TIME" IS '下载时间';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."STATUS" IS '状态: 0-未启用, 1-已启用, 2-已废弃';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."ACTIVE_TIME" IS '启用时间';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."REMARK" IS '备注';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_TEMPLATE_INFO"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE UNIQUE INDEX "UK_TEMPLATE_INFO_ID" ON "T_TEMPLATE_INFO"("TEMPLATE_ID");
CREATE INDEX "IDX_TEMPLATE_INFO_CODE" ON "T_TEMPLATE_INFO"("TEMPLATE_CODE");
CREATE INDEX "IDX_TEMPLATE_INFO_BUS_ID" ON "T_TEMPLATE_INFO"("BUSINESS_ID");
CREATE INDEX "IDX_TEMPLATE_INFO_STATUS" ON "T_TEMPLATE_INFO"("STATUS");

-- ============================================================
-- 模板采集频率表 (接口3: tempDownload - 采集频率)
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_TEMPLATE_FREQUENCY" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "FREQUENCY_ID" VARCHAR(100) NOT NULL,
    "TEMPLATE_ID" VARCHAR(100) NOT NULL,
    "FIELD_CODE" VARCHAR(100),
    "FIELD_NAME" VARCHAR(200),
    "COLLECT_FREQUENCY" VARCHAR(50),
    "COLLECT_TIME" VARCHAR(50),
    "IS_REQUIRED" INT DEFAULT 0,
    "DATA_TYPE" VARCHAR(50),
    "DATA_FORMAT" VARCHAR(100),
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_TEMPLATE_FREQUENCY" IS '模板采集频率表';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."ID" IS '主键ID';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."FREQUENCY_ID" IS '频率主键ID';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."TEMPLATE_ID" IS '模板外键ID';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."FIELD_CODE" IS '字段编码';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."FIELD_NAME" IS '字段名称';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."COLLECT_FREQUENCY" IS '采集频率: DAILY-每日, WEEKLY-每周, MONTHLY-每月, QUARTERLY-每季度, YEARLY-每年';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."COLLECT_TIME" IS '采集时间点';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."IS_REQUIRED" IS '是否必填: 0-否, 1-是';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."DATA_TYPE" IS '数据类型';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."DATA_FORMAT" IS '数据格式';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."REMARK" IS '备注';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_TEMPLATE_FREQUENCY"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE UNIQUE INDEX "UK_TEMPLATE_FREQ_ID" ON "T_TEMPLATE_FREQUENCY"("FREQUENCY_ID");
CREATE INDEX "IDX_TEMPLATE_FREQ_TEMP_ID" ON "T_TEMPLATE_FREQUENCY"("TEMPLATE_ID");
CREATE INDEX "IDX_TEMPLATE_FREQ_FIELD" ON "T_TEMPLATE_FREQUENCY"("FIELD_CODE");

-- ============================================================
-- 补传任务表 (接口4: taskDownload)
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_SUPPLEMENT_TASK" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "LOG_ID" VARCHAR(100),
    "TASK_ID" VARCHAR(100) NOT NULL,
    "TASK_CODE" VARCHAR(50) NOT NULL,
    "TASK_NAME" VARCHAR(200),
    "BUSINESS_TYPE" VARCHAR(50),
    "TEMPLATE_ID" VARCHAR(100),
    "TEMPLATE_CODE" VARCHAR(50),
    "START_DATE" DATE,
    "END_DATE" DATE,
    "DEADLINE" DATETIME,
    "TASK_DESC" TEXT,
    "FILE_NAME" VARCHAR(500),
    "FILE_PATH" VARCHAR(1000),
    "TASK_CONTENT_DECRYPTED" TEXT,
    "DOWNLOAD_TIME" DATETIME,
    "TASK_STATUS" INT DEFAULT 0,
    "COMPLETE_TIME" DATETIME,
    "COMPLETE_RATE" DECIMAL(5,2),
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_SUPPLEMENT_TASK" IS '补传任务表';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."ID" IS '主键ID';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."LOG_ID" IS '关联日志ID';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."TASK_ID" IS '任务主键ID';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."TASK_CODE" IS '任务编码';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."TASK_NAME" IS '任务名称';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."BUSINESS_TYPE" IS '业务类型';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."TEMPLATE_ID" IS '模板ID';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."TEMPLATE_CODE" IS '模板编码';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."START_DATE" IS '补传开始日期';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."END_DATE" IS '补传结束日期';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."DEADLINE" IS '截止时间';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."TASK_DESC" IS '任务描述';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."FILE_NAME" IS '任务文件名';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."FILE_PATH" IS '任务文件路径';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."TASK_CONTENT_DECRYPTED" IS '任务内容(解密后)';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."DOWNLOAD_TIME" IS '下载时间';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."TASK_STATUS" IS '任务状态: 0-待执行, 1-执行中, 2-已完成, 3-已取消, 4-已过期';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."COMPLETE_TIME" IS '完成时间';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."COMPLETE_RATE" IS '完成率(%)';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."REMARK" IS '备注';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_SUPPLEMENT_TASK"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE UNIQUE INDEX "UK_SUPPLEMENT_TASK_ID" ON "T_SUPPLEMENT_TASK"("TASK_ID");
CREATE INDEX "IDX_SUPPLEMENT_TASK_CODE" ON "T_SUPPLEMENT_TASK"("TASK_CODE");
CREATE INDEX "IDX_SUPPLEMENT_BUS_TYPE" ON "T_SUPPLEMENT_TASK"("BUSINESS_TYPE");
CREATE INDEX "IDX_SUPPLEMENT_STATUS" ON "T_SUPPLEMENT_TASK"("TASK_STATUS");
CREATE INDEX "IDX_SUPPLEMENT_DEADLINE" ON "T_SUPPLEMENT_TASK"("DEADLINE");

-- ============================================================
-- 通知公告表 (接口5: noticeDownload)
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_NOTICE_ANNOUNCEMENT" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "LOG_ID" VARCHAR(100),
    "NOTICE_ID" VARCHAR(100) NOT NULL,
    "NOTICE_CODE" VARCHAR(50),
    "NOTICE_TITLE" VARCHAR(500),
    "NOTICE_TYPE" VARCHAR(50),
    "NOTICE_CONTENT" TEXT,
    "PERMISSION_CODE" VARCHAR(50),
    "FILE_NAME" VARCHAR(500),
    "FILE_PATH" VARCHAR(1000),
    "NOTICE_CONTENT_DECRYPTED" TEXT,
    "ATTACHMENT_COUNT" INT DEFAULT 0,
    "ATTACHMENT_INFO" TEXT,
    "DOWNLOAD_TIME" DATETIME,
    "PUBLISH_TIME" DATETIME,
    "READ_STATUS" INT DEFAULT 0,
    "READ_TIME" DATETIME,
    "IMPORTANCE" INT DEFAULT 0,
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_NOTICE_ANNOUNCEMENT" IS '通知公告表';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."ID" IS '主键ID';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."LOG_ID" IS '关联日志ID';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."NOTICE_ID" IS '通知主键ID';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."NOTICE_CODE" IS '通知编码';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."NOTICE_TITLE" IS '通知标题';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."NOTICE_TYPE" IS '通知类型: 0007-异常反馈通知, 0009-普通通知';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."NOTICE_CONTENT" IS '通知内容';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."PERMISSION_CODE" IS '权限编码';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."FILE_NAME" IS '通知文件名';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."FILE_PATH" IS '通知文件路径';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."NOTICE_CONTENT_DECRYPTED" IS '通知内容(解密后)';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."ATTACHMENT_COUNT" IS '附件数量';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."ATTACHMENT_INFO" IS '附件信息(JSON)';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."DOWNLOAD_TIME" IS '下载时间';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."PUBLISH_TIME" IS '发布时间';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."READ_STATUS" IS '阅读状态: 0-未读, 1-已读';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."READ_TIME" IS '阅读时间';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."IMPORTANCE" IS '重要程度: 0-普通, 1-重要, 2-紧急';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."REMARK" IS '备注';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_NOTICE_ANNOUNCEMENT"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE UNIQUE INDEX "UK_NOTICE_ID" ON "T_NOTICE_ANNOUNCEMENT"("NOTICE_ID");
CREATE INDEX "IDX_NOTICE_TYPE" ON "T_NOTICE_ANNOUNCEMENT"("NOTICE_TYPE");
CREATE INDEX "IDX_NOTICE_READ_STATUS" ON "T_NOTICE_ANNOUNCEMENT"("READ_STATUS");
CREATE INDEX "IDX_NOTICE_PUBLISH_TIME" ON "T_NOTICE_ANNOUNCEMENT"("PUBLISH_TIME");

-- ============================================================
-- 远程日志同步表 (接口6: logDownload)
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_REMOTE_LOG_SYNC" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "EL_ID" VARCHAR(100) NOT NULL,
    "BUSINESS_CODE" VARCHAR(50),
    "FILE_NAME" VARCHAR(500),
    "PUSH_DATE" DATETIME,
    "GRAB_DATE" DATETIME,
    "REPAIR_MARK" VARCHAR(100),
    "EL_CREATEDATE" DATETIME,
    "SYNC_TIME" DATETIME,
    "MODULE_CODE" VARCHAR(50),
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_REMOTE_LOG_SYNC" IS '远程日志同步表';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."ID" IS '主键ID';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."EL_ID" IS '远程日志主键ID';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."BUSINESS_CODE" IS '业务编码';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."FILE_NAME" IS '报送文件名称';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."PUSH_DATE" IS '推送时间';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."GRAB_DATE" IS '抓取时间';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."REPAIR_MARK" IS '补录标识: 1-正常上传, 0-主动补录, 其他-被动补录任务ID';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."EL_CREATEDATE" IS '日志生成时间';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."SYNC_TIME" IS '同步时间';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."MODULE_CODE" IS '模块编码: DATAPUSHLOG-报送文件日志, TEMP-采集目录日志';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."REMARK" IS '备注';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_REMOTE_LOG_SYNC"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE UNIQUE INDEX "UK_REMOTE_LOG_EL_ID" ON "T_REMOTE_LOG_SYNC"("EL_ID");
CREATE INDEX "IDX_REMOTE_LOG_BUS_CODE" ON "T_REMOTE_LOG_SYNC"("BUSINESS_CODE");
CREATE INDEX "IDX_REMOTE_LOG_PUSH_DATE" ON "T_REMOTE_LOG_SYNC"("PUSH_DATE");
CREATE INDEX "IDX_REMOTE_LOG_MODULE" ON "T_REMOTE_LOG_SYNC"("MODULE_CODE");

-- ============================================================
-- 接口配置表
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_INTERFACE_CONFIG" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "CONFIG_KEY" VARCHAR(100) NOT NULL,
    "CONFIG_VALUE" VARCHAR(1000),
    "CONFIG_DESC" VARCHAR(500),
    "CONFIG_GROUP" VARCHAR(50),
    "IS_ENCRYPTED" INT DEFAULT 0,
    "STATUS" INT DEFAULT 1,
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_INTERFACE_CONFIG" IS '接口配置表';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."ID" IS '主键ID';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."CONFIG_KEY" IS '配置键';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."CONFIG_VALUE" IS '配置值';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."CONFIG_DESC" IS '配置描述';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."CONFIG_GROUP" IS '配置分组';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."IS_ENCRYPTED" IS '是否加密: 0-否, 1-是';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."STATUS" IS '状态: 0-禁用, 1-启用';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."REMARK" IS '备注';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE UNIQUE INDEX "UK_INTERFACE_CONFIG_KEY" ON "T_INTERFACE_CONFIG"("CONFIG_KEY");
CREATE INDEX "IDX_INTERFACE_CONFIG_GROUP" ON "T_INTERFACE_CONFIG"("CONFIG_GROUP");

-- ============================================================
-- 初始化接口配置数据
-- ============================================================
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.server.host', 'http://localhost:8080', '前置服务器地址', 'SERVER');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.server.port', '8080', '前置服务器端口', 'SERVER');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.api.username', 'admin', '接口调用用户名', 'AUTH');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.api.password', 'admin123', '接口调用密码', 'AUTH');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.social.credit.code', '91110000000000000X', '企业社会信用代码', 'ENTERPRISE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.ah.status', '0', '安徽模式状态: 0-禁用, 1-启用', 'MODE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.file.upload.path', '/data/upload', '文件上传路径', 'FILE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.file.download.path', '/data/download', '文件下载路径', 'FILE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.file.key.path', '/data/download/keys', '密钥证书文件保存路径', 'FILE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.file.template.path', '/data/download/templates', '采集模板文件保存路径', 'FILE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.file.task.path', '/data/download/tasks', '补传任务文件保存路径', 'FILE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.file.notice.path', '/data/download/notices', '通知公告文件保存路径', 'FILE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.retry.max.count', '3', '最大重试次数', 'RETRY');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.retry.interval', '60000', '重试间隔(毫秒)', 'RETRY');

COMMIT;
