-- ============================================================
-- 国资委数据采集交换平台接口相关表 - 达梦数据库版本
-- ============================================================

-- ============================================================
-- 统一操作日志表 (所有接口调用的总日志)
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_INTERFACE_LOG" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "LOG_ID" VARCHAR(100) NOT NULL,
    "INTERFACE_TYPE" VARCHAR(50) NOT NULL,
    "INTERFACE_URL" VARCHAR(500),
    "REQUEST_METHOD" VARCHAR(10),
    "REQUEST_PARAMS" TEXT,
    "REQUEST_TIME" DATETIME,
    "RESPONSE_TIME" DATETIME,
    "COST_TIME" BIGINT,
    "RESPONSE_CODE" INT,
    "SERVICE_FLAG" VARCHAR(10),
    "RESPONSE_MSG" TEXT,
    "RESPONSE_BODY" TEXT,
    "FILE_NAME" VARCHAR(500),
    "FILE_SIZE" BIGINT,
    "FILE_PATH" VARCHAR(1000),
    "BUSINESS_TYPE" VARCHAR(50),
    "SOCIAL_CREDIT_CODE" VARCHAR(50),
    "STATUS" INT DEFAULT 0,
    "ERROR_MSG" TEXT,
    "RETRY_COUNT" INT DEFAULT 0,
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_INTERFACE_LOG" IS '接口调用统一日志表';
COMMENT ON COLUMN "T_INTERFACE_LOG"."ID" IS '主键ID';
COMMENT ON COLUMN "T_INTERFACE_LOG"."LOG_ID" IS '日志ID(UUID)';
COMMENT ON COLUMN "T_INTERFACE_LOG"."INTERFACE_TYPE" IS '接口类型: FILE_UPLOAD-数据报送, KEY_DOWNLOAD-密钥下载, TEMP_DOWNLOAD-采集目录下载, TASK_DOWNLOAD-任务下载, NOTICE_DOWNLOAD-通知下载, LOG_DOWNLOAD-日志下载';
COMMENT ON COLUMN "T_INTERFACE_LOG"."INTERFACE_URL" IS '接口地址';
COMMENT ON COLUMN "T_INTERFACE_LOG"."REQUEST_METHOD" IS '请求方法: GET/POST';
COMMENT ON COLUMN "T_INTERFACE_LOG"."REQUEST_PARAMS" IS '请求参数(JSON)';
COMMENT ON COLUMN "T_INTERFACE_LOG"."REQUEST_TIME" IS '请求时间';
COMMENT ON COLUMN "T_INTERFACE_LOG"."RESPONSE_TIME" IS '响应时间';
COMMENT ON COLUMN "T_INTERFACE_LOG"."COST_TIME" IS '耗时(毫秒)';
COMMENT ON COLUMN "T_INTERFACE_LOG"."RESPONSE_CODE" IS '响应状态码';
COMMENT ON COLUMN "T_INTERFACE_LOG"."SERVICE_FLAG" IS '服务标识: 0-失败, 1-成功, 2-无权限, 3-无新文件';
COMMENT ON COLUMN "T_INTERFACE_LOG"."RESPONSE_MSG" IS '响应消息';
COMMENT ON COLUMN "T_INTERFACE_LOG"."RESPONSE_BODY" IS '响应内容';
COMMENT ON COLUMN "T_INTERFACE_LOG"."FILE_NAME" IS '文件名称';
COMMENT ON COLUMN "T_INTERFACE_LOG"."FILE_SIZE" IS '文件大小(字节)';
COMMENT ON COLUMN "T_INTERFACE_LOG"."FILE_PATH" IS '文件保存路径';
COMMENT ON COLUMN "T_INTERFACE_LOG"."BUSINESS_TYPE" IS '业务类型';
COMMENT ON COLUMN "T_INTERFACE_LOG"."SOCIAL_CREDIT_CODE" IS '社会信用代码';
COMMENT ON COLUMN "T_INTERFACE_LOG"."STATUS" IS '处理状态: 0-未处理, 1-处理中, 2-处理成功, 3-处理失败';
COMMENT ON COLUMN "T_INTERFACE_LOG"."ERROR_MSG" IS '错误信息';
COMMENT ON COLUMN "T_INTERFACE_LOG"."RETRY_COUNT" IS '重试次数';
COMMENT ON COLUMN "T_INTERFACE_LOG"."REMARK" IS '备注';
COMMENT ON COLUMN "T_INTERFACE_LOG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_INTERFACE_LOG"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_INTERFACE_LOG"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_INTERFACE_LOG"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_INTERFACE_LOG"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE INDEX "IDX_INTERFACE_LOG_LOG_ID" ON "T_INTERFACE_LOG"("LOG_ID");
CREATE INDEX "IDX_INTERFACE_LOG_TYPE" ON "T_INTERFACE_LOG"("INTERFACE_TYPE");
CREATE INDEX "IDX_INTERFACE_LOG_REQ_TIME" ON "T_INTERFACE_LOG"("REQUEST_TIME");
CREATE INDEX "IDX_INTERFACE_LOG_STATUS" ON "T_INTERFACE_LOG"("STATUS");
CREATE INDEX "IDX_INTERFACE_LOG_BUS_TYPE" ON "T_INTERFACE_LOG"("BUSINESS_TYPE");

-- ============================================================
-- 数据报送记录表 (接口1: fileUpload)
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_FILE_UPLOAD_RECORD" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "LOG_ID" VARCHAR(100),
    "API_CODE" VARCHAR(50),
    "BUSINESS_TYPE" VARCHAR(50),
    "FILE_NAME" VARCHAR(500) NOT NULL,
    "FILE_SIZE" BIGINT,
    "FILE_PATH" VARCHAR(1000),
    "FILE_MD5" VARCHAR(100),
    "SOCIAL_CREDIT_CODE" VARCHAR(50),
    "UPLOAD_STATUS" INT DEFAULT 0,
    "SERVICE_FLAG" VARCHAR(10),
    "RESPONSE_MSG" TEXT,
    "PARSE_STATUS" INT DEFAULT 0,
    "PARSE_RESULT" TEXT,
    "ERROR_MSG" TEXT,
    "RETRY_COUNT" INT DEFAULT 0,
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_FILE_UPLOAD_RECORD" IS '数据报送记录表';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."ID" IS '主键ID';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."LOG_ID" IS '关联日志ID';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."API_CODE" IS 'API编码';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."BUSINESS_TYPE" IS '业务类型';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."FILE_NAME" IS '文件名称';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."FILE_SIZE" IS '文件大小(字节)';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."FILE_PATH" IS '文件保存路径';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."FILE_MD5" IS '文件MD5值';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."SOCIAL_CREDIT_CODE" IS '企业社会信用代码';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."UPLOAD_STATUS" IS '上传状态: 0-待处理, 1-处理中, 2-成功, 3-失败';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."SERVICE_FLAG" IS '服务标识: 0-失败, 1-成功, 2-无权限';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."RESPONSE_MSG" IS '响应消息';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."PARSE_STATUS" IS '解析状态: 0-未解析, 1-解析中, 2-解析成功, 3-解析失败';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."PARSE_RESULT" IS '解析结果(JSON)';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."ERROR_MSG" IS '错误信息';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."RETRY_COUNT" IS '重试次数';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."REMARK" IS '备注';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_FILE_UPLOAD_RECORD"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE INDEX "IDX_FILE_UPLOAD_LOG_ID" ON "T_FILE_UPLOAD_RECORD"("LOG_ID");
CREATE INDEX "IDX_FILE_UPLOAD_BUS_TYPE" ON "T_FILE_UPLOAD_RECORD"("BUSINESS_TYPE");
CREATE INDEX "IDX_FILE_UPLOAD_STATUS" ON "T_FILE_UPLOAD_RECORD"("UPLOAD_STATUS");
CREATE INDEX "IDX_FILE_UPLOAD_CREATE_TIME" ON "T_FILE_UPLOAD_RECORD"("CREATE_TIME");

-- ============================================================
-- 密钥证书表 (接口2: keyDownload)
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_KEY_CERTIFICATE" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "LOG_ID" VARCHAR(100),
    "KEY_ID" VARCHAR(100) NOT NULL,
    "BUSINESS_TYPE" VARCHAR(50),
    "KEY_VERSION" VARCHAR(50),
    "SM2_PUBLIC_KEY" TEXT,
    "SM4_KEY" TEXT,
    "SM2_PUBLIC_KEY_DECRYPTED" TEXT,
    "SM4_KEY_DECRYPTED" TEXT,
    "FILE_NAME" VARCHAR(500),
    "FILE_PATH" VARCHAR(1000),
    "DOWNLOAD_TIME" DATETIME,
    "STATUS" INT DEFAULT 0,
    "ACTIVE_TIME" DATETIME,
    "EXPIRE_TIME" DATETIME,
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_KEY_CERTIFICATE" IS '密钥证书表';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."ID" IS '主键ID';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."LOG_ID" IS '关联日志ID';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."KEY_ID" IS '密钥主键ID';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."BUSINESS_TYPE" IS '业务类型';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."KEY_VERSION" IS '密钥版本号';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."SM2_PUBLIC_KEY" IS 'SM2公钥(加密存储)';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."SM4_KEY" IS 'SM4密钥(加密存储)';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."SM2_PUBLIC_KEY_DECRYPTED" IS 'SM2公钥(解密后明文)';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."SM4_KEY_DECRYPTED" IS 'SM4密钥(解密后明文)';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."FILE_NAME" IS '密钥文件名';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."FILE_PATH" IS '文件保存路径';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."DOWNLOAD_TIME" IS '下载时间';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."STATUS" IS '状态: 0-未启用, 1-已启用, 2-已废弃';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."ACTIVE_TIME" IS '启用时间';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."EXPIRE_TIME" IS '过期时间';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."REMARK" IS '备注';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_KEY_CERTIFICATE"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE UNIQUE INDEX "UK_KEY_CERT_KEY_ID" ON "T_KEY_CERTIFICATE"("KEY_ID");
CREATE INDEX "IDX_KEY_CERT_BUS_TYPE" ON "T_KEY_CERTIFICATE"("BUSINESS_TYPE");
CREATE INDEX "IDX_KEY_CERT_VERSION" ON "T_KEY_CERTIFICATE"("KEY_VERSION");
CREATE INDEX "IDX_KEY_CERT_STATUS" ON "T_KEY_CERTIFICATE"("STATUS");


-- ============================================================
-- 接口配置表
-- ============================================================
CREATE TABLE IF NOT EXISTS "T_INTERFACE_CONFIG" (
    "ID" BIGINT IDENTITY(1,1) PRIMARY KEY,
    "CONFIG_KEY" VARCHAR(100) NOT NULL,
    "CONFIG_VALUE" VARCHAR(1000),
    "CONFIG_DESC" VARCHAR(500),
    "CONFIG_GROUP" VARCHAR(50),
    "IS_ENCRYPTED" INT DEFAULT 0,
    "STATUS" INT DEFAULT 1,
    "REMARK" VARCHAR(500),
    "CREATE_TIME" DATETIME DEFAULT SYSDATE,
    "UPDATE_TIME" DATETIME DEFAULT SYSDATE,
    "CREATE_BY" VARCHAR(50) DEFAULT 'system',
    "UPDATE_BY" VARCHAR(50) DEFAULT 'system',
    "DELETED" INT DEFAULT 0
);

COMMENT ON TABLE "T_INTERFACE_CONFIG" IS '接口配置表';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."ID" IS '主键ID';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."CONFIG_KEY" IS '配置键';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."CONFIG_VALUE" IS '配置值';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."CONFIG_DESC" IS '配置描述';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."CONFIG_GROUP" IS '配置分组';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."IS_ENCRYPTED" IS '是否加密: 0-否, 1-是';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."STATUS" IS '状态: 0-禁用, 1-启用';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."REMARK" IS '备注';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "T_INTERFACE_CONFIG"."DELETED" IS '逻辑删除: 0-未删除 1-已删除';

CREATE UNIQUE INDEX "UK_INTERFACE_CONFIG_KEY" ON "T_INTERFACE_CONFIG"("CONFIG_KEY");
CREATE INDEX "IDX_INTERFACE_CONFIG_GROUP" ON "T_INTERFACE_CONFIG"("CONFIG_GROUP");

-- ============================================================
-- 初始化接口配置数据
-- ============================================================
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.server.host', 'http://localhost:8080', '前置服务器地址', 'SERVER');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.server.port', '8080', '前置服务器端口', 'SERVER');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.api.username', 'admin', '接口调用用户名', 'AUTH');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.api.password', 'admin123', '接口调用密码', 'AUTH');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.social.credit.code', '91110000000000000X', '企业社会信用代码', 'ENTERPRISE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.ah.status', '0', '安徽模式状态: 0-禁用, 1-启用', 'MODE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.file.upload.path', '/data/upload', '文件上传路径', 'FILE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.file.download.path', '/data/download', '文件下载路径', 'FILE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.file.key.path', '/data/download/keys', '密钥证书文件保存路径', 'FILE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.file.template.path', '/data/download/templates', '采集模板文件保存路径', 'FILE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.file.task.path', '/data/download/tasks', '补传任务文件保存路径', 'FILE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.file.notice.path', '/data/download/notices', '通知公告文件保存路径', 'FILE');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.retry.max.count', '3', '最大重试次数', 'RETRY');
INSERT INTO "T_INTERFACE_CONFIG" ("CONFIG_KEY", "CONFIG_VALUE", "CONFIG_DESC", "CONFIG_GROUP") VALUES
('preposed.retry.interval', '60000', '重试间隔(毫秒)', 'RETRY');

-- ============================================================
-- 同步记录表
-- ============================================================
-- 同步记录表（每次同步插入一条）
CREATE TABLE sync_record (
                             id              INT IDENTITY(1,1) PRIMARY KEY,
                             table_name      VARCHAR(100) NOT NULL,
                             sync_time       TIMESTAMP NOT NULL,
                             sync_count      INT DEFAULT 0,
                             sync_status     TINYINT DEFAULT 1,
                             create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             remark          VARCHAR(255)
);

-- 创建索引（按表名+时间查询最新记录）
CREATE INDEX idx_sync_record ON sync_record(table_name, sync_time DESC);

-- 注释
COMMENT ON TABLE sync_record IS '增量同步记录表';
COMMENT ON COLUMN sync_record.table_name IS '表名';
COMMENT ON COLUMN sync_record.sync_time IS '本次同步截止时间';
COMMENT ON COLUMN sync_record.sync_count IS '本次同步数据量';
COMMENT ON COLUMN sync_record.sync_status IS '状态: 0-失败 1-成功';

-- 初始化5张表的基准记录
INSERT INTO sync_record (table_name, sync_time, remark) VALUES ('SASAORGANIZATIONS', TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '初始化');
INSERT INTO sync_record (table_name, sync_time, remark) VALUES ('SASAOWNERSHIP', TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '初始化');
INSERT INTO sync_record (table_name, sync_time, remark) VALUES ('SASAEQUITYPART', TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '初始化');
INSERT INTO sync_record (table_name, sync_time, remark) VALUES ('SASAPERSONNEL', TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '初始化');
INSERT INTO sync_record (table_name, sync_time, remark) VALUES ('SASALAYERSTR', TO_TIMESTAMP('1970-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '初始化');


-- ============================================================
-- 创建数据上报记录表（主键自增）
-- ============================================================
-- 创建数据上报记录表（主键自增）
CREATE TABLE DATA_REPORT_RECORD (
                                    ID INT IDENTITY(1,1) PRIMARY KEY,
                                    TOTAL_COUNT NUMBER(10) DEFAULT 0,
                                    REPORT_DETAIL CLOB,
                                    IS_REPORTED NUMBER(1) DEFAULT 0,
                                    REMARK VARCHAR(500),
                                    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 添加字段注释
COMMENT ON TABLE DATA_REPORT_RECORD IS '数据上报记录表';
COMMENT ON COLUMN DATA_REPORT_RECORD.ID IS '主键ID(自增)';
COMMENT ON COLUMN DATA_REPORT_RECORD.TOTAL_COUNT IS '上报数据总量';
COMMENT ON COLUMN DATA_REPORT_RECORD.REPORT_DETAIL IS '上报详情';
COMMENT ON COLUMN DATA_REPORT_RECORD.IS_REPORTED IS '是否上报(0:未上报 1:已上报)';
COMMENT ON COLUMN DATA_REPORT_RECORD.REMARK IS '备注';
COMMENT ON COLUMN DATA_REPORT_RECORD.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DATA_REPORT_RECORD.UPDATE_TIME IS '更新时间';


-- ============================================================
-- 通知公告下载记录表（主键自增）
-- ============================================================
-- 通知公告下载记录表
CREATE TABLE T_NOTICE_DOWNLOAD_RECORD (
                                          ID INT IDENTITY(1,1) PRIMARY KEY,
                                          REQUEST_URL VARCHAR(1000),
                                          REQUEST_TIME TIMESTAMP,
                                          RESPONSE_TIME TIMESTAMP,
                                          COST_TIME BIGINT,
                                          FILE_NAME VARCHAR(500),
                                          FILE_SIZE BIGINT,
                                          FILE_PATH VARCHAR(1000),
                                          NOTICE_TYPE VARCHAR(20),
                                          DOWNLOAD_STATUS INT DEFAULT 0,
                                          SERVICE_FLAG VARCHAR(10),
                                          RESPONSE_MSG TEXT,
                                          CONTENT_TYPE VARCHAR(100),
                                          RETRY_COUNT INT DEFAULT 0,
                                          ERROR_MSG TEXT,
                                          REMARK VARCHAR(500),
                                          CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                          UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建索引
CREATE INDEX IDX_NOTICE_DOWNLOAD_STATUS ON T_NOTICE_DOWNLOAD_RECORD(DOWNLOAD_STATUS);
CREATE INDEX IDX_NOTICE_DOWNLOAD_TIME ON T_NOTICE_DOWNLOAD_RECORD(CREATE_TIME);
CREATE INDEX IDX_NOTICE_REQUEST_TIME ON T_NOTICE_DOWNLOAD_RECORD(REQUEST_TIME);
CREATE INDEX IDX_NOTICE_TYPE ON T_NOTICE_DOWNLOAD_RECORD(NOTICE_TYPE);

-- 注释
COMMENT ON TABLE T_NOTICE_DOWNLOAD_RECORD IS '通知公告下载记录表';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.ID IS '主键ID';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.REQUEST_URL IS '请求URL';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.REQUEST_TIME IS '请求时间';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.RESPONSE_TIME IS '响应时间';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.COST_TIME IS '耗时(毫秒)';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.FILE_NAME IS '文件名称';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.FILE_SIZE IS '文件大小(字节)';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.FILE_PATH IS '文件保存路径';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.NOTICE_TYPE IS '通知类型: 0007-异常反馈通知, 0009-普通通知';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.DOWNLOAD_STATUS IS '下载状态: 0-下载中, 1-成功, 2-失败, 3-无文件';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.SERVICE_FLAG IS '服务标识: 0-失败, 1-成功, 2-无权限';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.RESPONSE_MSG IS '响应消息';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.CONTENT_TYPE IS '响应ContentType';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.RETRY_COUNT IS '重试次数';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.ERROR_MSG IS '错误信息';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.REMARK IS '备注';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_NOTICE_DOWNLOAD_RECORD.UPDATE_TIME IS '更新时间';


-- ============================================================
-- 报送日志（主键自增）
-- ============================================================
-- 报送日志查询记录表
CREATE TABLE T_PUSH_LOG_RECORD (
                                   ID INT IDENTITY(1,1) PRIMARY KEY,
                                   REQUEST_URL VARCHAR(1000),
                                   REQUEST_BODY VARCHAR(1000),
                                   REQUEST_TIME TIMESTAMP,
                                   RESPONSE_TIME TIMESTAMP,
                                   COST_TIME BIGINT,
                                   START_DATE VARCHAR(20),
                                   END_DATE VARCHAR(20),
                                   REQUEST_STATUS INT DEFAULT 0,
                                   RESPONSE_JSON CLOB,
                                   ERROR_MSG TEXT,
                                   REMARK VARCHAR(500),
                                   CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                   UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_PUSH_LOG_STATUS ON T_PUSH_LOG_RECORD(REQUEST_STATUS);
CREATE INDEX IDX_PUSH_LOG_TIME ON T_PUSH_LOG_RECORD(CREATE_TIME);
CREATE INDEX IDX_PUSH_LOG_DATE ON T_PUSH_LOG_RECORD(START_DATE, END_DATE);

COMMENT ON TABLE T_PUSH_LOG_RECORD IS '报送日志查询记录表';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.ID IS '主键ID';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.REQUEST_URL IS '请求URL';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.REQUEST_BODY IS '请求参数';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.REQUEST_TIME IS '请求时间';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.RESPONSE_TIME IS '响应时间';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.COST_TIME IS '耗时(毫秒)';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.START_DATE IS '查询开始日期(yyyyMMdd)';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.END_DATE IS '查询结束日期(yyyyMMdd)';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.REQUEST_STATUS IS '请求状态: 0-请求中, 1-成功, 2-失败';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.RESPONSE_JSON IS '响应JSON';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.ERROR_MSG IS '错误信息';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.REMARK IS '备注';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_PUSH_LOG_RECORD.UPDATE_TIME IS '更新时间';

COMMIT;
